import { test, expect } from '@playwright/test'
import {
  PAGE_LOAD_TIMEOUT,
  getTestSession,
  setupAuthenticatedPage,
} from '../helpers'

// This test runs against the production-built preview server (port 5175)
// rather than the dev server, because the real service worker is only
// generated by `vite build` — dev mode produces a stub SW that doesn't
// precache the hashed JS bundles the app needs to boot.
const PREVIEW_BASE = 'http://localhost:5175'

test.describe('Offline cold-launch', () => {
  test('dashboard still renders after reload while offline', async ({
    page,
    context,
    request,
  }) => {
    const { token } = await getTestSession(
      request,
      'offline-cold-launch@example.com',
      'Offline User'
    )
    await setupAuthenticatedPage(page, token)

    // First visit: online, so the SW can install and populate the precache.
    await page.goto(`${PREVIEW_BASE}/`)
    await expect(page.getByTestId('page-title')).toContainText('Dashboard', {
      timeout: PAGE_LOAD_TIMEOUT,
    })

    // Wait for the SW to be controlling the page. With clientsClaim: true in
    // the workbox config, this happens as soon as the SW activates.
    await page.waitForFunction(
      () => navigator.serviceWorker.controller !== null,
      null,
      { timeout: 15_000 }
    )

    // Wait for the workbox precache to exist and be non-empty. Without this
    // check, we could race the SW install and cut the network before
    // index.html is actually in the cache.
    await page.waitForFunction(
      async () => {
        const keys = await caches.keys()
        const precacheName = keys.find((k) => k.startsWith('workbox-precache'))
        if (!precacheName) return false
        const cache = await caches.open(precacheName)
        const entries = await cache.keys()
        return entries.length > 0
      },
      null,
      { timeout: 15_000 }
    )

    // Cut the network at the browser level — no request reaches the server.
    // The service worker is still running; it just can't fetch().
    await context.setOffline(true)

    try {
      // Cold-launch simulation: reload the page. The SW must intercept the
      // navigation and serve the precached index.html without attempting
      // (and failing) a network fetch.
      //
      // Under the cache-nuke bug we just fixed, the SW's handler would throw
      // because its precache was empty, and the browser would render its own
      // error page ("FetchEvent.respondWith received an error").
      await page.reload()

      // Dashboard renders because the SW served index.html + precached JS
      // bundles, and the auth/pool state is hydrated from localStorage and
      // IndexedDB (both populated during the online visit above).
      await expect(page.getByTestId('page-title')).toContainText('Dashboard', {
        timeout: PAGE_LOAD_TIMEOUT,
      })
    } finally {
      await context.setOffline(false)
    }
  })
})
