[settings.general]
mise = true

[daemons.backend]
run = "mise run dev"
dir = "backend"
port = 9292
auto = [ "start", "stop" ]
env = { FRONTEND_URL = "https://tayaway.localhost" }

[daemons.frontend]
run = "mise run dev"
dir = "frontend"
depends = [ "backend" ]
port = 5173
auto = [ "start", "stop" ]
env = { FRONTEND_HOST = "127.0.0.1" }
