plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - vendor/**/*

Performance:
  Enabled: true

Layout:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: false

Metrics:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/BlockForwarding:
  Enabled: false

Style:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  Exclude:
    - Gemfile

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 50

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 9
