source "https://rubygems.org"

ruby "~> 4.0.0"

# Web framework
gem "puma"
gem "roda", "~> 3.98"

# Database
gem "pg"
gem "sequel"
gem "sequel_pg", require: "sequel"

# JSON
gem "json"
gem "jwt"

# Environment
gem "dotenv"

# Autoloading
gem "zeitwerk"

# Runtime type checking
gem "sorbet-static-and-runtime", require: "sorbet-runtime"

# Tasks
gem "rake"

group :development do
  gem "concurrent-ruby-ext", require: false

  # listen for file changes
  gem "listen", require: false

  gem "rubocop", require: false
  gem "rubocop-factory_bot", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-sequel", require: false
  gem "rubocop-sorbet", require: false
end

group :development, :test do
  gem "tapioca", ">= 0.17.10", require: false
end

group :test do
  gem "database_cleaner-sequel"
  gem "factory_bot"
  gem "rack-test"
  gem "rspec"
end
