# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-http` gem.
# Please instead update this file by running `bin/tapioca gem async-http`.


# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:6
module Async; end

# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:7
module Async::HTTP; end

# pkg:gem/async-http#lib/async/http/body/writable.rb:11
module Async::HTTP::Body; end

# Invokes a callback once the body has finished reading.
#
# pkg:gem/async-http#lib/async/http/statistics.rb:32
class Async::HTTP::Body::Statistics < ::Protocol::HTTP::Body::Wrapper
  # @return [Statistics] a new instance of Statistics
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:33
  def initialize(start_time, body, callback); end

  # pkg:gem/async-http#lib/async/http/statistics.rb:63
  def close(error = T.unsafe(nil)); end

  # Returns the value of attribute end_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:47
  def end_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:57
  def first_chunk_duration; end

  # Returns the value of attribute first_chunk_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:46
  def first_chunk_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:95
  def inspect; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:69
  def read; end

  # Returns the value of attribute sent.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:49
  def sent; end

  # Returns the value of attribute start_time.
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:45
  def start_time; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:81
  def to_s; end

  # pkg:gem/async-http#lib/async/http/statistics.rb:51
  def total_duration; end

  private

  # pkg:gem/async-http#lib/async/http/statistics.rb:101
  def complete_statistics(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/statistics.rb:107
  def format_duration(seconds); end
end

# pkg:gem/async-http#lib/async/http/body/writable.rb:12
Async::HTTP::Body::Writable = Protocol::HTTP::Body::Writable

# A protocol specifies a way in which to communicate with a remote peer.
#
# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:8
module Async::HTTP::Protocol; end

# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:36
module Async::HTTP::Protocol::Configurable
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:37
  def new(**options); end
end

# pkg:gem/async-http#lib/async/http/protocol/configurable.rb:9
class Async::HTTP::Protocol::Configured
  # @return [Configured] a new instance of Configured
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:10
  def initialize(protocol, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:21
  def client(peer, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:31
  def names; end

  # Returns the value of attribute options.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:19
  def options; end

  # Returns the value of attribute protocol.
  #
  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:16
  def protocol; end

  # pkg:gem/async-http#lib/async/http/protocol/configurable.rb:26
  def server(peer, **options); end
end

# This module provides a default instance of the protocol, which can be used to create clients and servers. The name is a play on "Default" + "Singleton".
#
# pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:10
module Async::HTTP::Protocol::Defaulton
  # Create a client for an outbound connection, using the default instance.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:18
  def client(peer, **options); end

  # Returns the value of attribute default.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:15
  def default; end

  # Sets the attribute default
  #
  # @param value the value to set the attribute default to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:15
  def default=(_arg0); end

  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:28
  def names; end

  # Create a server for an inbound connection, using the default instance.
  #
  # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:23
  def server(peer, **options); end

  class << self
    # @private
    #
    # pkg:gem/async-http#lib/async/http/protocol/defaulton.rb:11
    def extended(base); end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:11
module Async::HTTP::Protocol::HTTP1
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:23
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:36
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:53
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:46
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1.rb:28
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http10.rb:12
module Async::HTTP::Protocol::HTTP10
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:18
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:31
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:48
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:41
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http10.rb:23
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http10.rb:15
Async::HTTP::Protocol::HTTP10::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http11.rb:13
module Async::HTTP::Protocol::HTTP11
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:19
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:32
    def client(peer, **options); end

    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:49
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:42
    def server(peer, **options); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http11.rb:24
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http11.rb:16
Async::HTTP::Protocol::HTTP11::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:12
class Async::HTTP::Protocol::HTTP1::Client < ::Async::HTTP::Protocol::HTTP1::Connection
  # @return [Client] a new instance of Client
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:13
  def initialize(*_arg0, **_arg1, &_arg2); end

  # Used by the client to send requests to the remote server.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:32
  def call(request, task: T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:21
  def closed(error = T.unsafe(nil)); end

  # Returns the value of attribute pool.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:19
  def pool; end

  # Sets the attribute pool
  #
  # @param value the value to set the attribute pool to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/client.rb:19
  def pool=(_arg0); end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:16
class Async::HTTP::Protocol::HTTP1::Connection < ::Protocol::HTTP1::Connection
  # @return [Connection] a new instance of Connection
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:17
  def initialize(stream, version, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:28
  def as_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:52
  def concurrency; end

  # Returns the value of attribute count.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:50
  def count; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:38
  def http1?; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:42
  def http2?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:46
  def peer; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:61
  def reusable?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:32
  def to_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:24
  def to_s; end

  # Returns the value of attribute version.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:36
  def version; end

  # Can we use this connection to make requests?
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/connection.rb:57
  def viable?; end
end

# Keeps track of whether a body is being read, and if so, waits for it to be closed.
#
# pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:14
class Async::HTTP::Protocol::HTTP1::Finishable < ::Protocol::HTTP::Body::Wrapper
  # @return [Finishable] a new instance of Finishable
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:15
  def initialize(body); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:34
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:55
  def inspect; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:28
  def read; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:24
  def reading?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/finishable.rb:43
  def wait(persistent = T.unsafe(nil)); end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:12
class Async::HTTP::Protocol::HTTP1::Request < ::Async::HTTP::Protocol::Request
  # @return [Request] a new instance of Request
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:45
  def initialize(connection, scheme, authority, method, path, version, headers, body); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:54
  def connection; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:62
  def hijack!; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:58
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:66
  def write_interim_response(status, headers = T.unsafe(nil)); end

  class << self
    # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:25
    def read(connection); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:13
    def valid_path?(target); end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:43
Async::HTTP::Protocol::HTTP1::Request::UPGRADE = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http1/request.rb:23
Async::HTTP::Protocol::HTTP1::Request::URI_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:13
class Async::HTTP::Protocol::HTTP1::Response < ::Async::HTTP::Protocol::Response
  # @return [Response] a new instance of Response
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:32
  def initialize(connection, version, status, reason, headers, body); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:50
  def connection; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:58
  def hijack!; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:54
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:42
  def pool=(pool); end

  # Returns the value of attribute reason.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:29
  def reason; end

  class << self
    # pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:14
    def read(connection, request); end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http1/response.rb:26
Async::HTTP::Protocol::HTTP1::Response::UPGRADE = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:19
class Async::HTTP::Protocol::HTTP1::Server < ::Async::HTTP::Protocol::HTTP1::Connection
  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:20
  def initialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:26
  def closed(error = T.unsafe(nil)); end

  # Server loop.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:63
  def each(task: T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:32
  def fail_request(status); end

  # pkg:gem/async-http#lib/async/http/protocol/http1/server.rb:41
  def next_request; end
end

# pkg:gem/async-http#lib/async/http/protocol/http1.rb:20
Async::HTTP::Protocol::HTTP1::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:11
module Async::HTTP::Protocol::HTTP2
  extend ::Async::HTTP::Protocol::Configurable

  class << self
    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:23
    def bidirectional?; end

    # Create a client for an outbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:54
    def client(peer, settings: T.unsafe(nil)); end

    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:79
    def names; end

    # Create a server for an inbound connection.
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:68
    def server(peer, settings: T.unsafe(nil)); end

    # @return [Boolean]
    #
    # pkg:gem/async-http#lib/async/http/protocol/http2.rb:28
    def trailer?; end
  end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:21
Async::HTTP::Protocol::HTTP2::AUTHORITY = T.let(T.unsafe(nil), String)

# The default settings for the client.
#
# pkg:gem/async-http#lib/async/http/protocol/http2.rb:33
Async::HTTP::Protocol::HTTP2::CLIENT_SETTINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:26
Async::HTTP::Protocol::HTTP2::CONNECTION = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:25
Async::HTTP::Protocol::HTTP2::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:15
class Async::HTTP::Protocol::HTTP2::Client < ::Protocol::HTTP2::Client
  include ::Async::HTTP::Protocol::HTTP2::Connection

  # @return [Client] a new instance of Client
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:18
  def initialize(stream); end

  # Used by the client to send requests to the remote server.
  #
  # @raise [::Protocol::HTTP2::Error]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:31
  def call(request); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:26
  def create_response; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:45
  def read_response(response); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/client.rb:41
  def write_request(response, request); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:29
module Async::HTTP::Protocol::HTTP2::Connection
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:30
  def initialize(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:47
  def as_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:69
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:115
  def concurrency; end

  # Returns the value of attribute count.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:113
  def count; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:57
  def http1?; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:61
  def http2?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:109
  def peer; end

  # Returns the value of attribute promises.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:107
  def promises; end

  # @raise [RuntimeError]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:80
  def read_in_background(parent: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:124
  def reusable?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:65
  def start_connection; end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:55
  def stream; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:39
  def synchronize(&block); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:51
  def to_json(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:43
  def to_s; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:128
  def version; end

  # Can we use this connection to make requests?
  #
  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:120
  def viable?; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:17
Async::HTTP::Protocol::HTTP2::HTTPS = T.let(T.unsafe(nil), String)

# A writable body which requests window updates when data is read from it.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:13
class Async::HTTP::Protocol::HTTP2::Input < ::Protocol::HTTP::Body::Writable
  # @return [Input] a new instance of Input
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:14
  def initialize(stream, length); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/input.rb:21
  def read; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:19
Async::HTTP::Protocol::HTTP2::METHOD = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:12
class Async::HTTP::Protocol::HTTP2::Output
  # @return [Output] a new instance of Output
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:13
  def initialize(stream, body, trailer = T.unsafe(nil)); end

  # This method should only be called from within the context of the output task.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:73
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:65
  def close_write(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:26
  def start(parent: T.unsafe(nil)); end

  # This method should only be called from within the context of the HTTP/2 stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:79
  def stop(error); end

  # Returns the value of attribute trailer.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:24
  def trailer; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:36
  def window_updated(size); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:44
  def write(chunk); end

  private

  # Reads chunks from the given body and writes them to the stream as fast as possible.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:101
  def passthrough(task); end

  # Send `maximum_size` bytes of data using the specified `stream`. If the buffer has no more chunks, `END_STREAM` will be sent on the final chunk.
  #
  # @param maximum_size [Integer] send up to this many bytes of data.
  # @param stream [Stream] the stream to use for sending data frames.
  # @return [String, nil] any data that could not be written.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:127
  def send_data(chunk, maximum_size); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/output.rb:88
  def stream(task); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:20
Async::HTTP::Protocol::HTTP2::PATH = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:23
Async::HTTP::Protocol::HTTP2::PROTOCOL = T.let(T.unsafe(nil), String)

# Typically used on the server side to represent an incoming request, and write the response.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:14
class Async::HTTP::Protocol::HTTP2::Request < ::Async::HTTP::Protocol::Request
  # @return [Request] a new instance of Request
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:89
  def initialize(stream); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:97
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:105
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:113
  def send_response(response); end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:95
  def stream; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:101
  def valid?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:146
  def write_interim_response(status, headers = T.unsafe(nil)); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:109
Async::HTTP::Protocol::HTTP2::Request::NO_RESPONSE = T.let(T.unsafe(nil), Array)

# pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:15
class Async::HTTP::Protocol::HTTP2::Request::Stream < ::Async::HTTP::Protocol::HTTP2::Stream
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:16
  def initialize(*_arg0); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:82
  def closed(error); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:25
  def receive_initial_headers(headers, end_stream); end

  # Returns the value of attribute request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/request.rb:23
  def request; end
end

# Typically used on the client side for writing a request and reading the incoming response.
#
# pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:14
class Async::HTTP::Protocol::HTTP2::Response < ::Async::HTTP::Protocol::Response
  # @return [Response] a new instance of Response
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:130
  def initialize(stream); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:166
  def build_request(headers); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:150
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:158
  def head?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:140
  def pool=(pool); end

  # Returns the value of attribute request.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:138
  def request; end

  # Send a request and read it into this response.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:199
  def send_request(request); end

  # Returns the value of attribute stream.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:137
  def stream; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:162
  def valid?; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:154
  def wait; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:15
class Async::HTTP::Protocol::HTTP2::Response::Stream < ::Async::HTTP::Protocol::HTTP2::Stream
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:16
  def initialize(*_arg0); end

  # @raise [ProtocolError]
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:35
  def accept_push_promise_stream(promised_stream_id, headers); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:117
  def closed(error); end

  # Notify anyone waiting on the response headers to be received (or failure).
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:100
  def notify!; end

  # This should be invoked from the background reader, and notifies the task waiting for the headers that we are done.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:40
  def receive_initial_headers(headers, end_stream); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:89
  def receive_interim_headers(status, headers); end

  # Returns the value of attribute response.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:25
  def response; end

  # Wait for the headers to be received or for stream reset.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:108
  def wait; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/response.rb:27
  def wait_for_input; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:18
Async::HTTP::Protocol::HTTP2::SCHEME = T.let(T.unsafe(nil), String)

# The default settings for the server.
#
# pkg:gem/async-http#lib/async/http/protocol/http2.rb:41
Async::HTTP::Protocol::HTTP2::SERVER_SETTINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:22
Async::HTTP::Protocol::HTTP2::STATUS = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:15
class Async::HTTP::Protocol::HTTP2::Server < ::Protocol::HTTP2::Server
  include ::Async::HTTP::Protocol::HTTP2::Connection

  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:18
  def initialize(stream); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:31
  def accept_stream(stream_id); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:37
  def close(error = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:47
  def each(task: T.unsafe(nil)); end

  # Returns the value of attribute requests.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/server.rb:29
  def requests; end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:17
class Async::HTTP::Protocol::HTTP2::Stream < ::Protocol::HTTP2::Stream
  # @return [Stream] a new instance of Stream
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:18
  def initialize(*_arg0); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:39
  def add_header(key, value, trailer: T.unsafe(nil)); end

  # When the stream transitions to the closed state, this method is called. There are roughly two ways this can happen:
  # - A frame is received which causes this stream to enter the closed state. This method will be invoked from the background reader task.
  # - A frame is sent which causes this stream to enter the closed state. This method will be invoked from that task.
  # While the input stream is relatively straight forward, the output stream can trigger the second case above
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:157
  def closed(error); end

  # Called when the output terminates normally.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:126
  def finish_output(error = T.unsafe(nil)); end

  # Returns the value of attribute headers.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:33
  def headers; end

  # Sets the attribute headers
  #
  # @param value the value to set the attribute headers to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:33
  def headers=(_arg0); end

  # Returns the value of attribute input.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:37
  def input; end

  # Returns the value of attribute pool.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:35
  def pool; end

  # Sets the attribute pool
  #
  # @param value the value to set the attribute pool to.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:35
  def pool=(_arg0); end

  # Prepare the input stream which will be used for incoming data frames.
  #
  # @return [Input] the input body.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:83
  def prepare_input(length); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:98
  def process_data(frame); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:57
  def process_headers(frame); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:51
  def receive_trailing_headers(headers, end_stream); end

  # Set the body and begin sending it.
  #
  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:119
  def send_body(body, trailer = T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:91
  def update_local_window(frame); end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:77
  def wait_for_input; end

  # pkg:gem/async-http#lib/async/http/protocol/http2/stream.rb:145
  def window_updated(size); end
end

# pkg:gem/async-http#lib/async/http/protocol/http2/connection.rb:27
Async::HTTP::Protocol::HTTP2::TRAILER = T.let(T.unsafe(nil), String)

# pkg:gem/async-http#lib/async/http/protocol/http2.rb:20
Async::HTTP::Protocol::HTTP2::VERSION = T.let(T.unsafe(nil), String)

# A server that supports both HTTP1.0 and HTTP1.1 semantics by detecting the version of the request.
#
# pkg:gem/async-http#lib/async/http/protocol/https.rb:17
class Async::HTTP::Protocol::HTTPS
  extend ::Async::HTTP::Protocol::Defaulton

  # @return [HTTPS] a new instance of HTTPS
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:26
  def initialize(handlers = T.unsafe(nil), **options); end

  # pkg:gem/async-http#lib/async/http/protocol/https.rb:31
  def add(name, protocol, **options); end

  # Create a client for an outbound connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:59
  def client(peer, **options); end

  # pkg:gem/async-http#lib/async/http/protocol/https.rb:78
  def names; end

  # Determine the protocol of the peer and return the appropriate protocol class.
  #
  # Use TLS Application Layer Protocol Negotiation (ALPN) to determine the protocol.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:42
  def protocol_for(peer); end

  # Create a server for an inbound connection.
  #
  # pkg:gem/async-http#lib/async/http/protocol/https.rb:70
  def server(peer, **options); end
end

# The protocol classes for each supported protocol.
#
# pkg:gem/async-http#lib/async/http/protocol/https.rb:19
Async::HTTP::Protocol::HTTPS::HANDLERS = T.let(T.unsafe(nil), Hash)

# This is generated by server protocols.
#
# pkg:gem/async-http#lib/async/http/protocol/request.rb:19
class Async::HTTP::Protocol::Request < ::Protocol::HTTP::Request
  # pkg:gem/async-http#lib/async/http/protocol/request.rb:20
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/request.rb:24
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:39
  def inspect; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:31
  def peer; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:35
  def remote_address; end

  # pkg:gem/async-http#lib/async/http/protocol/request.rb:28
  def write_interim_response(status, headers = T.unsafe(nil)); end
end

# Failed to send the request. The request body has NOT been consumed (i.e. #read) and you should retry the request.
#
# pkg:gem/async-http#lib/async/http/protocol/request.rb:15
class Async::HTTP::Protocol::RequestFailed < ::StandardError; end

# This is generated by client protocols.
#
# pkg:gem/async-http#lib/async/http/protocol/response.rb:14
class Async::HTTP::Protocol::Response < ::Protocol::HTTP::Response
  # pkg:gem/async-http#lib/async/http/protocol/response.rb:15
  def connection; end

  # @return [Boolean]
  #
  # pkg:gem/async-http#lib/async/http/protocol/response.rb:19
  def hijack?; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:31
  def inspect; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:23
  def peer; end

  # pkg:gem/async-http#lib/async/http/protocol/response.rb:27
  def remote_address; end
end

# pkg:gem/async-http#lib/async/http/server.rb:15
class Async::HTTP::Server < ::Protocol::HTTP::Middleware
  # @return [Server] a new instance of Server
  #
  # pkg:gem/async-http#lib/async/http/server.rb:20
  def initialize(app, endpoint, protocol: T.unsafe(nil), scheme: T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/server.rb:44
  def accept(peer, address, task: T.unsafe(nil)); end

  # pkg:gem/async-http#lib/async/http/server.rb:28
  def as_json(*_arg0, **_arg1, &_arg2); end

  # Returns the value of attribute endpoint.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:40
  def endpoint; end

  # Returns the value of attribute protocol.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:41
  def protocol; end

  # pkg:gem/async-http#lib/async/http/server.rb:64
  def run; end

  # Returns the value of attribute scheme.
  #
  # pkg:gem/async-http#lib/async/http/server.rb:42
  def scheme; end

  # pkg:gem/async-http#lib/async/http/server.rb:36
  def to_json(*_arg0, **_arg1, &_arg2); end

  class << self
    # pkg:gem/async-http#lib/async/http/server.rb:16
    def for(*arguments, **options, &block); end
  end
end

# pkg:gem/async-http#lib/async/http/statistics.rb:12
class Async::HTTP::Statistics
  # @return [Statistics] a new instance of Statistics
  #
  # pkg:gem/async-http#lib/async/http/statistics.rb:17
  def initialize(start_time); end

  # pkg:gem/async-http#lib/async/http/statistics.rb:21
  def wrap(response, &block); end

  class << self
    # pkg:gem/async-http#lib/async/http/statistics.rb:13
    def start; end
  end
end

# pkg:gem/async-http#lib/async/http/body/writable.rb:12
class Protocol::HTTP::Body::Writable < ::Protocol::HTTP::Body::Readable; end
