# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-utilization` gem.
# Please instead update this file by running `bin/tapioca gem async-utilization`.


# pkg:gem/async-utilization#lib/async/utilization/version.rb:7
module Async; end

# Provides high-performance utilization metrics for Async services using shared memory.
#
# This module provides a convenient interface for tracking utilization metrics
# that can be synchronized to shared memory for inter-process communication.
# Registries should be explicitly created and passed to components that need them.
#
# See the {file:guides/getting-started/readme.md Getting Started} guide for usage examples.
#
# pkg:gem/async-utilization#lib/async/utilization/version.rb:9
module Async::Utilization; end

# A cached metric reference that avoids hash lookups on the fast path.
#
# This class caches all the details needed to write directly to shared memory,
# including the buffer, offset, and type. When the observer changes, the cache
# is invalidated and rebuilt on the next access.
#
# pkg:gem/async-utilization#lib/async/utilization/metric.rb:13
class Async::Utilization::Metric
  # Initialize a new metric.
  #
  # @return [Metric] a new instance of Metric
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:28
  def initialize(name); end

  # Decrement the metric value.
  #
  # Uses the fast path (direct buffer write) when cache is valid and observer is available.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:109
  def decrement; end

  # Returns the value of attribute guard.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:45
  def guard; end

  # Increment the metric value.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:77
  def increment; end

  # Returns the value of attribute name.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:39
  def name; end

  # Set the observer and rebuild cache.
  #
  # This is called when the registry assigns a new observer (or removes it).
  # The cache is invalidated and then immediately recomputed so that the
  # fast write path doesn't need to re-check the observer on the first write.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:54
  def observer=(observer); end

  # Set the metric value.
  #
  # Uses the fast path (direct buffer write) when cache is valid and observer is available.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:123
  def set(value); end

  # Track an operation: increment before the block, decrement after it completes.
  #
  # Returns the block's return value. Use for active/count metrics that should
  # reflect the number of operations currently in progress.
  #
  # @raise [ArgumentError]
  # @yield The operation to track.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:93
  def track(&block); end

  # Returns the value of attribute value.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:42
  def value; end

  protected

  # Write directly to the cached buffer if available.
  #
  # This is the fast path that avoids hash lookups. Always ensures cache is valid
  # first. If there's no observer or buffer, silently does nothing.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:139
  def write_direct(value); end

  class << self
    # Create a new metric for the given field and observer.
    #
    # pkg:gem/async-utilization#lib/async/utilization/metric.rb:19
    def for(field, observer); end
  end
end

# Shared memory observer for utilization metrics.
#
# Writes metrics to shared memory using a schema to define the
# serialization layout. The schema is required to know how to
# serialize values efficiently.
#
# pkg:gem/async-utilization#lib/async/utilization/observer.rb:15
class Async::Utilization::Observer
  # Initialize a new shared memory observer.
  #
  # @return [Observer] a new instance of Observer
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:63
  def initialize(schema, buffer); end

  # Returns the value of attribute buffer.
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:72
  def buffer; end

  # Returns the value of attribute schema.
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:69
  def schema; end

  class << self
    # Open a shared memory observer from a file.
    #
    # Maps the shared memory file and creates an Observer instance.
    # The file descriptor is closed after mapping - the memory mapping
    # persists independently on Unix/Linux systems.
    #
    # Note: mmap requires page-aligned offsets and sizes. This method handles
    # non-page-aligned offsets by mapping from the nearest page boundary
    # and adjusting field offsets accordingly.
    #
    # pkg:gem/async-utilization#lib/async/utilization/observer.rb:31
    def open(schema, path, size, offset); end
  end
end

# Registry for emitting utilization metrics.
#
# The registry tracks values directly and notifies a registered observer
# when values change. The observer (like Observer) can write to its backend.
#
# Registries should be explicitly created and passed to components that need them.
# In service contexts, registries are typically created via the evaluator and
# shared across components within the same service instance.
#
# When an observer is added, it is immediately notified of all current values
# so it can sync its state. When values change, the observer is notified.
#
# @example Create a registry and emit metrics:
#   registry = Async::Utilization::Registry.new
#
#   # Emit metrics - values tracked in registry
#   registry.increment(:total_requests)
#   registry.track(:active_requests) do
#   # Handle request - auto-decrements when block completes
#   end
#
#   # Add shared memory observer when supervisor connects
#   # Observer will be notified of all current values automatically
#   schema = Async::Utilization::Schema.build(
#   total_requests: :u64,
#   active_requests: :u32
#   )
#   observer = Async::Utilization::Observer.open(schema, "/path/to/shm", 4096, 0)
#   registry.observer = observer
#
# pkg:gem/async-utilization#lib/async/utilization/registry.rb:39
class Async::Utilization::Registry
  # Initialize a new registry.
  #
  # @return [Registry] a new instance of Registry
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:42
  def initialize; end

  # Decrement a field value.
  #
  # Delegates to the metric instance for the given field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:122
  def decrement(field); end

  # Returns the value of attribute guard.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:53
  def guard; end

  # Increment a field value.
  #
  # Delegates to the metric instance for the given field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:101
  def increment(field); end

  # Get a cached metric reference for a field.
  #
  # Returns a {Metric} instance that caches all details needed for fast writes.
  # Metrics are cached per field and invalidated when the observer changes.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:133
  def metric(field); end

  # Returns the value of attribute observer.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:50
  def observer; end

  # Set the observer for the registry.
  #
  # When an observer is set, all cached metrics are updated so they write
  # directly to the observer's buffer. The observer must expose `schema`
  # and `buffer` attributes.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:71
  def observer=(observer); end

  # Set a field value.
  #
  # Delegates to the metric instance for the given field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:91
  def set(field, value); end

  # Track an operation: increment before the block, decrement after it completes.
  #
  # Delegates to the metric instance for the given field.
  #
  # @yield The operation to track.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:112
  def track(field, &block); end

  # Get the current values for all metrics.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:58
  def values; end
end

# Defines a schema for shared memory serialization.
#
# The schema defines the layout and types for serializing utilization
# metrics to shared memory. It's only needed when using Observer for
# shared memory storage - the Registry itself doesn't require a schema.
#
# @example Assign a schema to an observer:
#   schema = Async::Utilization::Schema.build(
#   total_requests: :u64,
#   active_requests: :u32,
#   )
#
#   registry = Async::Utilization::Registry.new
#   observer = Async::Utilization::Observer.open(schema, "/path/to/shm", 4096, 0)
#   registry.observer = observer
#
# pkg:gem/async-utilization#lib/async/utilization/schema.rb:23
class Async::Utilization::Schema
  # Initialize a new schema.
  #
  # @return [Schema] a new instance of Schema
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:49
  def initialize(fields); end

  # Get field information for a given field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:67
  def [](field); end

  # Returns the value of attribute fields.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:61
  def fields; end

  # Convert schema to array format for shared memory.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:74
  def to_a; end

  class << self
    # Build a schema from raw fields.
    #
    # Factory method that takes a hash of field names to types and creates
    # Field instances with calculated offsets.
    #
    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:34
    def build(fields); end
  end
end

# Represents a field in the schema with its name, type, and offset.
#
# pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
class Async::Utilization::Schema::Field < ::Data
  # Returns the value of attribute name
  #
  # @return [Object] the current value of name
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def name; end

  # Returns the value of attribute offset
  #
  # @return [Object] the current value of offset
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def offset; end

  # Returns the value of attribute type
  #
  # @return [Object] the current value of type
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def type; end

  class << self
    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def [](*_arg0); end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def inspect; end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def members; end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def new(*_arg0); end
  end
end

# pkg:gem/async-utilization#lib/async/utilization/version.rb:10
Async::Utilization::VERSION = T.let(T.unsafe(nil), String)
