# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `database_cleaner-sequel` gem.
# Please instead update this file by running `bin/tapioca gem database_cleaner-sequel`.


# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/version.rb:1
module DatabaseCleaner; end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/version.rb:2
module DatabaseCleaner::Sequel; end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/base.rb:5
class DatabaseCleaner::Sequel::Base < ::DatabaseCleaner::Strategy
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/base.rb:6
  def db; end
end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/deletion.rb:5
class DatabaseCleaner::Sequel::Deletion < ::DatabaseCleaner::Sequel::Truncation
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/deletion.rb:35
  def clean; end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/deletion.rb:29
  def delete_tables(db, tables); end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/deletion.rb:6
  def disable_referential_integrity(tables); end
end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/transaction.rb:5
class DatabaseCleaner::Sequel::Transaction < ::DatabaseCleaner::Sequel::Base
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/transaction.rb:18
  def clean; end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/transaction.rb:6
  def start; end
end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:5
class DatabaseCleaner::Sequel::Truncation < ::DatabaseCleaner::Sequel::Base
  # @return [Truncation] a new instance of Truncation
  #
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:6
  def initialize(opts = T.unsafe(nil)); end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:16
  def clean; end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:12
  def start; end

  private

  # @return [Boolean]
  #
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:56
  def dirty?; end

  # overwritten
  #
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:72
  def migration_storage_names; end

  # @return [Boolean]
  #
  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:76
  def pre_count?; end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:43
  def pre_count_tables(tables); end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:67
  def tables_to_truncate(db); end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:47
  def truncate_tables(db, tables); end

  # pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/truncation.rb:60
  def txid; end
end

# pkg:gem/database_cleaner-sequel#lib/database_cleaner/sequel/version.rb:3
DatabaseCleaner::Sequel::VERSION = T.let(T.unsafe(nil), String)
