# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `falcon` gem.
# Please instead update this file by running `bin/tapioca gem falcon`.


# pkg:gem/falcon#lib/falcon/version.rb:7
module Falcon; end

# pkg:gem/falcon#lib/falcon/body/request_finished.rb:10
module Falcon::Body; end

# Wraps a response body and decrements a metric after the body is closed.
#
# Runs close on the underlying body first (which invokes rack.response_finished),
# then decrements the metric. Use this so requests_active stays elevated until
# the request is fully finished (including response_finished callbacks).
#
# pkg:gem/falcon#lib/falcon/body/request_finished.rb:16
class Falcon::Body::RequestFinished < ::Protocol::HTTP::Body::Wrapper
  # @return [RequestFinished] a new instance of RequestFinished
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:34
  def initialize(body, metric); end

  # Closes the underlying body (invoking rack.response_finished), then decrements the metric.
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:53
  def close(error = T.unsafe(nil)); end

  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:46
  def rewind; end

  # @return [Boolean]
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:41
  def rewindable?; end

  class << self
    # Wrap a response body with a metric. If the body is nil or empty, decrements immediately.
    #
    # pkg:gem/falcon#lib/falcon/body/request_finished.rb:22
    def wrap(message, metric); end
  end
end

# A composite server that manages multiple {Server} instances.
#
# This class coordinates running multiple server instances concurrently, allowing you to:
# - Serve different applications on different endpoints.
# - Use different configurations per server.
# - Access statistics for each named server.
# - Control all servers as a single unit.
#
# @example Create and run several applications.
#   require 'falcon/composite_server'
#   require 'falcon/server'
#
#   # Create individual servers
#   servers = {
#   "http" => Falcon::Server.new(app1, endpoint1),
#   "https" => Falcon::Server.new(app2, endpoint2)
#   }
#
#   # Create the composite server
#   composite = Falcon::CompositeServer.new(servers)
#
#   # Run all servers
#   composite.run
#
# pkg:gem/falcon#lib/falcon/composite_server.rb:32
class Falcon::CompositeServer
  # Initialize a composite server with the given server instances.
  #
  # @return [CompositeServer] a new instance of CompositeServer
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:36
  def initialize(servers); end

  # Get detailed statistics for each server.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:73
  def detailed_statistics; end

  # Run the composite server, starting all individual servers.
  #
  # This method should be called within an Async context. It will run all server instances concurrently.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:49
  def run; end

  # The individual server instances mapped by name.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:42
  def servers; end

  # Generates a human-readable string representing statistics for all servers.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:64
  def statistics_string; end
end

# pkg:gem/falcon#lib/falcon/middleware/verbose.rb:10
module Falcon::Middleware; end

# A HTTP middleware for logging requests and responses.
#
# pkg:gem/falcon#lib/falcon/middleware/verbose.rb:12
class Falcon::Middleware::Verbose < ::Protocol::HTTP::Middleware
  # Initialize the verbose middleware.
  #
  # @return [Verbose] a new instance of Verbose
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:16
  def initialize(app, logger = T.unsafe(nil)); end

  # Log details of the incoming request.
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:23
  def annotate(request); end

  # Log details of the incoming request using {annotate} and wrap the response to log response details too.
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:33
  def call(request); end
end

# A server listening on a specific endpoint, hosting a specific middleware.
#
# pkg:gem/falcon#lib/falcon/server.rb:19
class Falcon::Server < ::Async::HTTP::Server
  # Initialize the server and set up statistics tracking.
  #
  # @return [Server] a new instance of Server
  #
  # pkg:gem/falcon#lib/falcon/server.rb:45
  def initialize(*arguments, utilization_registry: T.unsafe(nil), **options); end

  # Accept a new connection and track connection statistics.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:58
  def accept(*_arg0, **_arg1, &_arg2); end

  # Handle a request and track request statistics.
  #
  # Uses manual increment/decrement so requests_active stays elevated until the
  # response body is closed (including rack.response_finished). The
  # Body::RequestFinished wrapper runs the decrement after the body closes,
  # so response_finished callbacks are counted as active.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:71
  def call(*_arg0, **_arg1, &_arg2); end

  # Generates a human-readable string representing the current statistics.
  #
  # e.g. `C=23/3.42K R=2/3.42K L=0.273`
  #
  # This can be interpreted as:
  #
  # - `C=23/3.42K` - The number of connections currently open and the total number of connections accepted.
  # - `R=2/3.42K` - The number of requests currently being processed and the total number of requests received.
  # - `L=0.273` - The average scheduler load of the server, where 0.0 is idle and 1.0 is fully loaded.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:89
  def statistics_string; end

  private

  # pkg:gem/falcon#lib/falcon/server.rb:95
  def format_count(value); end

  class << self
    # Wrap a rack application into a middleware suitable the server.
    #
    # pkg:gem/falcon#lib/falcon/server.rb:24
    def middleware(rack_app, verbose: T.unsafe(nil), cache: T.unsafe(nil)); end
  end
end

# pkg:gem/falcon#lib/falcon/version.rb:8
Falcon::VERSION = T.let(T.unsafe(nil), String)
