# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fido_metadata` gem.
# Please instead update this file by running `bin/tapioca gem fido_metadata`.


# A very simple cache story for the test suite that mimics the ActiveSupport::Cache::Store interface
#
# pkg:gem/fido_metadata#lib/fido_metadata/refinement/fixed_length_secure_compare.rb:5
module FidoMetadata
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata.rb:7
    def configuration; end

    # @yield [configuration]
    #
    # pkg:gem/fido_metadata#lib/fido_metadata.rb:15
    def configure; end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/attributes.rb:4
module FidoMetadata::Attributes
  # pkg:gem/fido_metadata#lib/fido_metadata/attributes.rb:27
  def from_json(hash = T.unsafe(nil)); end

  # pkg:gem/fido_metadata#lib/fido_metadata/attributes.rb:15
  def json_accessor(name, coercer = T.unsafe(nil)); end

  private

  # pkg:gem/fido_metadata#lib/fido_metadata/attributes.rb:5
  def underscore_name(name); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:6
class FidoMetadata::AuthenticatorGetInfo
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:11
  def aaguid; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:11
  def aaguid=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:18
  def algorithms; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:18
  def algorithms=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:27
  def certifications; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:27
  def certifications=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:10
  def extensions; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:10
  def extensions=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:22
  def firmware_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:22
  def firmware_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:20
  def force_pin_change; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:20
  def force_pin_change=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:23
  def max_cred_blob_length; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:23
  def max_cred_blob_length=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:15
  def max_credential_count_in_list; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:15
  def max_credential_count_in_list=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:16
  def max_credential_id_length; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:16
  def max_credential_id_length=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:13
  def max_msg_size; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:13
  def max_msg_size=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:24
  def max_rpi_ds_for_set_min_pin_length; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:24
  def max_rpi_ds_for_set_min_pin_length=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:19
  def max_serialized_large_blob_array; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:19
  def max_serialized_large_blob_array=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:21
  def min_pin_length; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:21
  def min_pin_length=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:12
  def options; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:12
  def options=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:14
  def pin_uv_auth_protocols; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:14
  def pin_uv_auth_protocols=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:25
  def preferred_platform_uv_attempts; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:25
  def preferred_platform_uv_attempts=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:28
  def remaining_discoverable_credentials; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:28
  def remaining_discoverable_credentials=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:17
  def transports; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:17
  def transports=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:26
  def uv_modality; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:26
  def uv_modality=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:29
  def vendor_prototype_config_commands; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:29
  def vendor_prototype_config_commands=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:9
  def versions; end

  # pkg:gem/fido_metadata#lib/fido_metadata/authenticator_get_info.rb:9
  def versions=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:6
class FidoMetadata::BiometricAccuracyDescriptor
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:13
  def block_slowdown; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:13
  def block_slowdown=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:12
  def max_retries; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:12
  def max_retries=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:11
  def max_templates; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:11
  def max_templates=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:10
  def self_attested_far; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:10
  def self_attested_far=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:9
  def self_attested_frr; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_accuracy_descriptor.rb:9
  def self_attested_frr=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:7
class FidoMetadata::BiometricStatusReport
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:10
  def cert_level; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:10
  def cert_level=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:14
  def certificate_number; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:14
  def certificate_number=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:13
  def certification_descriptor; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:13
  def certification_descriptor=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:15
  def certification_policy_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:15
  def certification_policy_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:16
  def certification_requirements_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:16
  def certification_requirements_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:12
  def effective_date; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:12
  def effective_date=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:11
  def modality; end

  # pkg:gem/fido_metadata#lib/fido_metadata/biometric_status_report.rb:11
  def modality=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:11
class FidoMetadata::Client
  # pkg:gem/fido_metadata#lib/fido_metadata/client.rb:26
  def download_toc(uri, algorithms: T.unsafe(nil), trusted_certs: T.unsafe(nil)); end

  private

  # pkg:gem/fido_metadata#lib/fido_metadata/client.rb:65
  def download_crls(certificates); end

  # pkg:gem/fido_metadata#lib/fido_metadata/client.rb:80
  def extract_crl_distribution_points(certificates); end

  # pkg:gem/fido_metadata#lib/fido_metadata/client.rb:45
  def get(uri); end

  # pkg:gem/fido_metadata#lib/fido_metadata/client.rb:56
  def http(uri); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:18
FidoMetadata::Client::DEFAULT_HEADERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:12
class FidoMetadata::Client::DataIntegrityError < ::StandardError; end

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:22
FidoMetadata::Client::FIDO_ROOT_CERTIFICATES = T.let(T.unsafe(nil), Array)

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:13
class FidoMetadata::Client::InvalidHashError < ::FidoMetadata::Client::DataIntegrityError; end

# pkg:gem/fido_metadata#lib/fido_metadata/client.rb:14
class FidoMetadata::Client::UnverifiedSigningKeyError < ::FidoMetadata::Client::DataIntegrityError; end

# pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:6
class FidoMetadata::CodeAccuracyDescriptor
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:9
  def base; end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:9
  def base=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:12
  def block_slowdown; end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:12
  def block_slowdown=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:11
  def max_retries; end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:11
  def max_retries=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:10
  def min_length; end

  # pkg:gem/fido_metadata#lib/fido_metadata/code_accuracy_descriptor.rb:10
  def min_length=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/date.rb:6
module FidoMetadata::Coercer; end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/assumed_value.rb:5
class FidoMetadata::Coercer::AssumedValue
  # @return [AssumedValue] a new instance of AssumedValue
  #
  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/assumed_value.rb:6
  def initialize(assume); end

  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/assumed_value.rb:10
  def coerce(value); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/authenticator_get_info.rb:7
module FidoMetadata::Coercer::AuthenticatorGetInfo
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/authenticator_get_info.rb:8
    def coerce(value); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/bit_field.rb:5
class FidoMetadata::Coercer::BitField
  # @return [BitField] a new instance of BitField
  #
  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/bit_field.rb:6
  def initialize(mapping, single_value: T.unsafe(nil)); end

  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/bit_field.rb:11
  def coerce(value); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/certificates.rb:7
module FidoMetadata::Coercer::Certificates
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/certificates.rb:8
    def coerce(values); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/date.rb:7
module FidoMetadata::Coercer::Date
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/date.rb:8
    def coerce(value); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/escaped_uri.rb:7
module FidoMetadata::Coercer::EscapedURI
  class << self
    # The character # is a reserved character and not allowed in URLs, it is replaced by its hex value %x23.
    # https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html#idl-def-MetadataTOCPayloadEntry
    #
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/escaped_uri.rb:10
    def coerce(value); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/magic_number.rb:5
class FidoMetadata::Coercer::MagicNumber
  # @return [MagicNumber] a new instance of MagicNumber
  #
  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/magic_number.rb:6
  def initialize(mapping, array: T.unsafe(nil)); end

  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/magic_number.rb:11
  def coerce(values); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/objects.rb:5
class FidoMetadata::Coercer::Objects
  # @return [Objects] a new instance of Objects
  #
  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/objects.rb:6
  def initialize(klass); end

  # pkg:gem/fido_metadata#lib/fido_metadata/coercer/objects.rb:10
  def coerce(values); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/statement.rb:7
module FidoMetadata::Coercer::Statement
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/statement.rb:8
    def coerce(value); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata/coercer/user_verification_details.rb:7
class FidoMetadata::Coercer::UserVerificationDetails
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/coercer/user_verification_details.rb:8
    def coerce(values); end
  end
end

# pkg:gem/fido_metadata#lib/fido_metadata.rb:19
class FidoMetadata::Configuration
  # Returns the value of attribute cache_backend.
  #
  # pkg:gem/fido_metadata#lib/fido_metadata.rb:20
  def cache_backend; end

  # Sets the attribute cache_backend
  #
  # @param value the value to set the attribute cache_backend to.
  #
  # pkg:gem/fido_metadata#lib/fido_metadata.rb:20
  def cache_backend=(_arg0); end

  # Returns the value of attribute race_condition_ttl.
  #
  # pkg:gem/fido_metadata#lib/fido_metadata.rb:21
  def race_condition_ttl; end

  # Sets the attribute race_condition_ttl
  #
  # @param value the value to set the attribute race_condition_ttl to.
  #
  # pkg:gem/fido_metadata#lib/fido_metadata.rb:21
  def race_condition_ttl=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:12
class FidoMetadata::Entry
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:16
  def aaguid; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:16
  def aaguid=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:15
  def aaid; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:15
  def aaid=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:17
  def attestation_certificate_key_identifiers; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:17
  def attestation_certificate_key_identifiers=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:20
  def biometric_status_reports; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:20
  def biometric_status_reports=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:18
  def hash; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:18
  def hash=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:25
  def metadata_statement; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:25
  def metadata_statement=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:24
  def rogue_list_hash; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:24
  def rogue_list_hash=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:23
  def rogue_list_url; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:23
  def rogue_list_url=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:21
  def status_reports; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:21
  def status_reports=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:22
  def time_of_last_status_change; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:22
  def time_of_last_status_change=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:19
  def url; end

  # pkg:gem/fido_metadata#lib/fido_metadata/entry.rb:19
  def url=(value); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:6
class FidoMetadata::PatternAccuracyDescriptor
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:11
  def block_slowdown; end

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:11
  def block_slowdown=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:10
  def max_retries; end

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:10
  def max_retries=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:9
  def min_complexity; end

  # pkg:gem/fido_metadata#lib/fido_metadata/pattern_accuracy_descriptor.rb:9
  def min_complexity=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/refinement/fixed_length_secure_compare.rb:6
module FidoMetadata::Refinement; end

# pkg:gem/fido_metadata#lib/fido_metadata/refinement/fixed_length_secure_compare.rb:7
module FidoMetadata::Refinement::FixedLengthSecureCompare; end

# pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:13
class FidoMetadata::Statement
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:18
  def aaguid; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:18
  def aaguid=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:17
  def aaid; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:17
  def aaid=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:21
  def alternative_descriptions; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:21
  def alternative_descriptions=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:34
  def attachment_hint; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:34
  def attachment_hint=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:19
  def attestation_certificate_key_identifiers; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:19
  def attestation_certificate_key_identifiers=(_arg0); end

  # Lazy load certificates for compatibility ActiveSupport::Cache. Can be removed once we require a version of
  # OpenSSL which includes https://github.com/ruby/openssl/pull/281
  #
  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:38
  def attestation_root_certificates; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:38
  def attestation_root_certificates=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:27
  def attestation_types; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:27
  def attestation_types=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:25
  def authentication_algorithms; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:25
  def authentication_algorithms=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:43
  def authenticator_get_info; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:43
  def authenticator_get_info=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:22
  def authenticator_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:22
  def authenticator_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:33
  def crypto_strength; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:33
  def crypto_strength=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:20
  def description; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:20
  def description=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:39
  def ecdaa_trust_anchors; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:39
  def ecdaa_trust_anchors=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:40
  def icon; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:40
  def icon=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:31
  def is_fresh_user_verification_required; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:31
  def is_fresh_user_verification_required=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:30
  def is_key_restricted; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:30
  def is_key_restricted=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:29
  def key_protection; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:29
  def key_protection=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:16
  def legal_header; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:16
  def legal_header=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:32
  def matcher_protection; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:32
  def matcher_protection=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:23
  def protocol_family; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:23
  def protocol_family=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:26
  def public_key_alg_and_encodings; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:26
  def public_key_alg_and_encodings=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:42
  def schema; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:42
  def schema=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:41
  def supported_extensions; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:41
  def supported_extensions=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:35
  def tc_display; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:35
  def tc_display=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:36
  def tc_display_content_type; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:36
  def tc_display_content_type=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:37
  def tc_display_png_characteristics; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:37
  def tc_display_png_characteristics=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:51
  def trust_store; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:24
  def upv; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:24
  def upv=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:28
  def user_verification_details; end

  # pkg:gem/fido_metadata#lib/fido_metadata/statement.rb:28
  def user_verification_details=(value); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:8
class FidoMetadata::StatusReport
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:13
  def certificate; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:13
  def certificate=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:16
  def certificate_number; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:16
  def certificate_number=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:15
  def certification_descriptor; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:15
  def certification_descriptor=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:17
  def certification_policy_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:17
  def certification_policy_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:18
  def certification_requirements_version; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:18
  def certification_requirements_version=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:12
  def effective_date; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:12
  def effective_date=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:11
  def status; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:11
  def status=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:14
  def url; end

  # pkg:gem/fido_metadata#lib/fido_metadata/status_report.rb:14
  def url=(value); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/store.rb:8
class FidoMetadata::Store
  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:26
  def fetch_entry(aaguid: T.unsafe(nil), attestation_certificate_key_id: T.unsafe(nil)); end

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:40
  def fetch_statement(aaguid: T.unsafe(nil), attestation_certificate_key_id: T.unsafe(nil)); end

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:13
  def table_of_contents; end

  private

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:76
  def cache_backend; end

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:84
  def client; end

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:80
  def race_condition_ttl; end

  # pkg:gem/fido_metadata#lib/fido_metadata/store.rb:66
  def verify_arguments(aaguid: T.unsafe(nil), attestation_certificate_key_id: T.unsafe(nil)); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/store.rb:9
FidoMetadata::Store::METADATA_ENDPOINT = T.let(T.unsafe(nil), URI::HTTPS)

# pkg:gem/fido_metadata#lib/fido_metadata/store.rb:11
FidoMetadata::Store::STATEMENT_CACHE_KEY = T.let(T.unsafe(nil), String)

# pkg:gem/fido_metadata#lib/fido_metadata/store.rb:10
FidoMetadata::Store::TOC_CACHE_KEY = T.let(T.unsafe(nil), String)

# pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:9
class FidoMetadata::TableOfContents
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:14
  def entries; end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:14
  def entries=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:17
  def expires_in; end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:12
  def legal_header; end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:12
  def legal_header=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:13
  def next_update; end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:13
  def next_update=(value); end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:15
  def no; end

  # pkg:gem/fido_metadata#lib/fido_metadata/table_of_contents.rb:15
  def no=(_arg0); end
end

# pkg:gem/fido_metadata#lib/fido_metadata/version.rb:4
FidoMetadata::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/fido_metadata#lib/fido_metadata/x5c_key_finder.rb:7
class FidoMetadata::VerificationError < ::StandardError; end

# pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:11
class FidoMetadata::VerificationMethodDescriptor
  extend ::FidoMetadata::Attributes

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:16
  def ba_desc; end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:16
  def ba_desc=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:15
  def ca_desc; end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:15
  def ca_desc=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:17
  def pa_desc; end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:17
  def pa_desc=(_arg0); end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:14
  def user_verification_method; end

  # pkg:gem/fido_metadata#lib/fido_metadata/verification_method_descriptor.rb:14
  def user_verification_method=(_arg0); end
end

# If the x5c header certificate chain can be validated by trusted root
# certificates, and none of the certificates are revoked, returns the public
# key from the first certificate.
# See https://tools.ietf.org/html/rfc7515#section-4.1.6
#
# pkg:gem/fido_metadata#lib/fido_metadata/x5c_key_finder.rb:13
class FidoMetadata::X5cKeyFinder
  class << self
    # pkg:gem/fido_metadata#lib/fido_metadata/x5c_key_finder.rb:14
    def from(x5c_header_or_certificates, trusted_certificates, crls); end

    private

    # pkg:gem/fido_metadata#lib/fido_metadata/x5c_key_finder.rb:40
    def build_store(trusted_certificates, crls); end

    # pkg:gem/fido_metadata#lib/fido_metadata/x5c_key_finder.rb:29
    def parse_certificates(x5c_header_or_certificates); end
  end
end
