# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mmdb` gem.
# Please instead update this file by running `bin/tapioca gem mmdb`.

# MaxMindDB provides IP geolocation lookup via a .mmdb database file.
# The mmdb gem wraps the native libmaxminddb C library.
class MaxMindDB
  sig { params(path: String).void }
  def initialize(path); end

  sig { params(ip: String).returns(T.nilable(T::Hash[Symbol, T.untyped])) }
  def lookup(ip); end

  sig { void }
  def close; end
end
