# typed: strict
# frozen_string_literal: true

# Minimal shim for rbnacl (libsodium bindings). The autogenerated RBI is
# typed: ignore because the gem relies on FFI, which Sorbet cannot resolve.
# We declare only what encryption.rb uses: SecretBox.nonce_bytes and
# SimpleBox.from_secret_key / SimpleBox#box / SimpleBox#open.

module RbNaCl
  class SecretBox
    sig { returns(Integer) }
    def self.nonce_bytes; end
  end

  class SimpleBox
    sig { params(key: String).returns(SimpleBox) }
    def self.from_secret_key(key); end

    sig { params(plaintext: String).returns(String) }
    def box(plaintext); end

    sig { params(ciphertext: String).returns(String) }
    def open(ciphertext); end
  end
end
